version: '3.8'

volumes:
    mongo_data:
        external: true
    redis_data:
        external: true

services:
    # Awful Auth
    redis:
        image: redis
        restart: unless-stopped
        command: redis-server --appendonly yes
        volumes:
        - redis_data:/data
    
    awful-auth:
        build:
            context: ../awful-auth
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - redis
        environment:
            SA_COOKIES_SESSION_ID: ${SA_COOKIES_SESSION_ID:?err}
            SA_COOKIES_SESSION_HASH: ${SA_COOKIES_SESSION_HASH:?err}
            SA_COOKIES_BB_USER_ID: ${SA_COOKIES_BB_USER_ID:?err}
            SA_COOKIES_BB_PASSWORD: ${SA_COOKIES_BB_PASSWORD:?err}
            CACHE_SYSTEM: redis
            CACHE_REDIS_ADDRESS: redis
    
    # Goon Files
    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?err}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?err}
        volumes:
            - mongo_data:/data/db
      
    goon-files:
        build:
            context: ../goon-files
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
        environment:
            DB_MONGO_HOST: mongo
            DB_MONGO_PORT: 27017
            DB_MONGO_USER: ${MONGO_USER:?err}
            DB_MONGO_PASS: ${MONGO_PASSWORD:?err}
            DB_MONGO_DB_NAME: goon-files
    
    # Discord Auth
    discord-auth:
        build:
            context: ../discord-auth
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - mongo
        ports:
            - 8080:80
        environment: 
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN:?err}
            DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID:?err}
            DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY:?err}
            AWFUL_AUTH_ADDRESS: http://awful-auth/
            GOON_FILES_ADDRESS: http://goon-files/
            DB_MONGO_HOST: mongo
            DB_MONGO_PORT: 27017
            DB_MONGO_USER: ${MONGO_USER:?err}
            DB_MONGO_PASS: ${MONGO_PASSWORD:?err}
            DB_MONGO_DB_NAME: discord-auth
